stages:
  - mavenbuild
  - maventest
  
maven-build:            
  stage: mavenbuild
  tags:
    - s4c_tag
  script:
    - cd Backend/BackendMain/springboot_example        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn package
  only:
    refs:
      - S4C_CICD
    changes:
      - Backend/**/*


maven-test:             
  stage: maventest
  tags:
    - s4c_tag
  script:
    - cd Backend/BackendMain/springboot_example
    - mvn test
  only:
    refs:
      - S4C_CICD
    changes:
      - Backend/**/*