stages:
  - mavenbuild
  - maventest

maven-build:
  stage: mavenbuild
  tags:
    - jj_tag
  script:
    - cd BackendMain
    - mvn package
  artifacts:
    paths:
      - BackendMain/springboot_example/target/*.jar
  only:
    refs:
      - JJ_CICD
    changes:
      - BackendMain/**/*

maven-test:
  stage: maventest
  tags:
    - jj_tag
  script:
    - cd BackendMain/springboot_example
    - mvn test
  only:
    refs:
      - JJ_CICD
    changes:
      - BackendMain/**/*